---
# tasks file for packages

- name: Running apt-get update and upgrade
  apt: upgrade=yes update_cache=yes


- name: Installing packages
  package:
    name: "{{ item }}"
  loop:
    - xserver-xorg-input-evdev
    - xserver-xorg-core
    - xinit
    - xterm
    - x11-xserver-utils
    - chromium-browser
    - unclutter
    - alsa-utils
    - libunwind8 
    - libunwind8-dev 
    - gettext 
    - libicu-dev 
    - liblttng-ust-dev 
    - libcurl4-openssl-dev 
    - libssl-dev 
    - uuid-dev 
    - unzip
    - nginx
    - fbi