---
# tasks file for packages

- name: Running apt-get update and upgrade
  apt: upgrade=yes update_cache=yes


- name: Installing packages
  apt: install_recommends=no 
  package:
    name: "{{ item }}"
  loop:
  - xserver-xorg-input-evdev
  - xserver-xorg-core
  - xinit
  - x11-xserver-utils
  - chromium-browser
  - unclutter
  - alsa-utils

